import { IDataTableHeader } from './IDataTable';

export const dataTableHeaderFixture: IDataTableHeader = {
  id: {
    visible: false,
  },
  firstname: {
    title: 'Firstname',
  },
  lastname: {
    title: 'Lastname',
  },
  age: {
    title: 'Age',
    slot: 'age',
    cssClass: 'ageColumn',
  },
  address: {
    title: 'Address',
  },
  created: {
    title: 'Created',
    slot: 'date',
  },
  updated: {
    title: 'Updated',
    slot: 'date',
  },
  actions: {
    title: 'Actions',
    slot: 'actions',
    sortable: false,
  },
};

export const dataTableDataFixture = [
  {
    id: 1,
    firstname: 'Toni',
    lastname: 'Stark',
    address: 'Wallstreet 1',
    age: 37,
    created: new Date('2010-10-10').getTime(),
    updated: new Date('2012-09-08').getTime(),
  },
  {
    id: 2,
    firstname: 'Richard',
    lastname: 'Brenson',
    address: 'Aurora',
    age: 19,
    created: new Date('2002-03-23').getTime(),
    updated: new Date('2009-06-14').getTime(),
  },
  {
    id: 3,
    firstname: 'Julia',
    lastname: 'Roberts',
    address: 'Elmstreet',
    age: 33,
    created: new Date('2004-04-04').getTime(),
    updated: new Date('2018-01-02').getTime(),
  },
  {
    id: 4,
    firstname: 'Justus',
    lastname: 'Jonas',
    address: 'Mainvalley',
    age: 56,
    created: new Date('1999-07-21').getTime(),
    updated: new Date('2014-09-30').getTime(),
  },
  {
    id: 5,
    firstname: 'Sheldon',
    lastname: 'Cooper',
    address: 'BigBang',
    age: 42,
    created: new Date('2013-02-02').getTime(),
    updated: new Date('2013-03-04').getTime(),
  },
  {
    id: 6,
    firstname: 'Toni',
    lastname: 'Stark',
    address: 'Wallstreet 1',
    age: 37,
    created: new Date('2010-10-10').getTime(),
    updated: new Date('2012-09-08').getTime(),
  },
  {
    id: 8,
    firstname: 'Julia',
    lastname: 'Roberts',
    address: 'Elmstreet',
    age: 33,
    created: new Date('2004-04-04').getTime(),
    updated: new Date('2018-01-02').getTime(),
  },
  {
    id: 10,
    firstname: 'Sheldon',
    lastname: 'Cooper',
    address: 'BigBang',
    age: 42,
    created: new Date('2013-02-02').getTime(),
    updated: new Date('2013-03-04').getTime(),
  },
  {
    id: 7,
    firstname: 'Richard',
    lastname: 'Brenson',
    address: 'Aurora',
    age: 19,
    created: new Date('2002-03-23').getTime(),
    updated: new Date('2009-06-14').getTime(),
  },
  {
    id: 9,
    firstname: 'Justus',
    lastname: 'Jonas',
    address: 'Mainvalley',
    age: 56,
    created: new Date('1999-07-21').getTime(),
    updated: new Date('2014-09-30').getTime(),
  },
  {
    id: 12,
    firstname: 'Richard',
    lastname: 'Brenson',
    address: 'Aurora',
    age: 19,
    created: new Date('2002-03-23').getTime(),
    updated: new Date('2009-06-14').getTime(),
  },
  {
    id: 11,
    firstname: 'Toni',
    lastname: 'Stark',
    address: 'Wallstreet 1',
    age: 37,
    created: new Date('2010-10-10').getTime(),
    updated: new Date('2012-09-08').getTime(),
  },
  {
    id: 14,
    firstname: 'Justus',
    lastname: 'Jonas',
    address: 'Mainvalley',
    age: 56,
    created: new Date('1999-07-21').getTime(),
    updated: new Date('2014-09-30').getTime(),
  },
  {
    id: 15,
    firstname: 'Sheldon',
    lastname: 'Cooper',
    address: 'BigBang',
    age: 42,
    created: new Date('2013-02-02').getTime(),
    updated: new Date('2013-03-04').getTime(),
  },
  {
    id: 18,
    firstname: 'Julia',
    lastname: 'Roberts',
    address: 'Elmstreet',
    age: 33,
    created: new Date('2004-04-04').getTime(),
    updated: new Date('2018-01-02').getTime(),
  },
  {
    id: 20,
    firstname: 'Sheldon',
    lastname: 'Cooper',
    address: 'BigBang',
    age: 42,
    created: new Date('2013-02-02').getTime(),
    updated: new Date('2013-03-04').getTime(),
  },
  {
    id: 13,
    firstname: 'Julia',
    lastname: 'Roberts',
    address: 'Elmstreet',
    age: 33,
    created: new Date('2004-04-04').getTime(),
    updated: new Date('2018-01-02').getTime(),
  },
  {
    id: 17,
    firstname: 'Richard',
    lastname: 'Brenson',
    address: 'Aurora',
    age: 19,
    created: new Date('2002-03-23').getTime(),
    updated: new Date('2009-06-14').getTime(),
  },
  {
    id: 19,
    firstname: 'Justus',
    lastname: 'Jonas',
    address: 'Mainvalley',
    age: 56,
    created: new Date('1999-07-21').getTime(),
    updated: new Date('2014-09-30').getTime(),
  },
  {
    id: 16,
    firstname: 'Toni',
    lastname: 'Stark',
    address: 'Wallstreet 1',
    age: 37,
    created: new Date('2010-10-10').getTime(),
    updated: new Date('2012-09-08').getTime(),
  },
];
