<template>
  <vue-box>
    <vue-tiles :class="$style.icons" :columns="[2, 6, 8]">
      <div v-for="icon in icons" :key="icon" :class="$style.icon">
        <component :is="`vue-icon-${icon}`" />
        {{ icon }}
      </div>
    </vue-tiles>
  </vue-box>
</template>

<script lang="ts">
/* istanbul ignore file */
import VueBox from '@/components/layout/VueBox/VueBox.vue';
import VueTiles from '@/components/layout/VueTiles/VueTiles.vue';

export default {
  name: 'IconList',
  components: {
    VueTiles,
    VueBox,
  },
  computed: {
    icons() {
      return [
        'academic-cap',
        'add-user',
        'adjustments',
        'annotation',
        'archive',
        'arrow-down',
        'arrow-left',
        'arrow-right',
        'arrow-up',
        'arrow-circle-down',
        'arrow-circle-left',
        'arrow-circle-right',
        'arrow-circle-up',
        'arrow-narrow-down',
        'arrow-narrow-left',
        'arrow-narrow-right',
        'arrow-narrow-up',
        'arrows-expand',
        'at-symbol',
        'badge-check',
        'ban',
        'beaker',
        'bell',
        'bookmark',
        'bookmark-alt',
        'book-open',
        'briefcase',
        'bullhorn',
        'cake',
        'calculator',
        'calendar',
        'camera',
        'cart',
        'certificate',
        'chart-bar',
        'chart-line',
        'chart-pie',
        'chart-square-bar',
        'chat',
        'chat-alt',
        'chat-alt-two',
        'checkmark',
        'checkmark-circle',
        'chevron-double-down',
        'chevron-double-left',
        'chevron-double-right',
        'chevron-double-up',
        'chevron-down',
        'chevron-left',
        'chevron-right',
        'chevron-up',
        'chip',
        'clipboard',
        'clipboard-check',
        'clipboard-copy',
        'clipboard-list',
        'clock',
        'cloud',
        'cloud-download',
        'cloud-upload',
        'code',
        'cog',
        'collection',
        'color-swatch',
        'credit-card',
        'cube',
        'cube-transparent',
        'currency-bangladeshi',
        'currency-dollar',
        'currency-euro',
        'currency-pound',
        'currency-rupee',
        'currency-yen',
        'cursor-click',
        'desktop-computer',
        'device-mobile',
        'device-mobile-alt',
        'device-tablet',
        'document',
        'document-add',
        'document-download',
        'document-duplicate',
        'document-remove',
        'document-report',
        'document-search',
        'document-text',
        'dots-circle-horizontal',
        'dots-horizontal',
        'dots-vertical',
        'download',
        'dribbble',
        'duplicate',
        'emoji-happy',
        'emoji-sad',
        'exclamation',
        'exclamation-circle',
        'external-link',
        'eye',
        'eye-off',
        'facebook',
        'fast-forward',
        'film',
        'filter',
        'finger-print',
        'fire',
        'flag',
        'folder',
        'folder-add',
        'folder-download',
        'folder-open',
        'folder-remove',
        'gift',
        'github',
        'github-alt',
        'globe',
        'globe-alt',
        'hand',
        'hashtag',
        'heart',
        'home',
        'identification',
        'inbox',
        'inbox-in',
        'info-circle',
        'instagram',
        'key',
        'library',
        'light-bulb',
        'lightning-bolt',
        'link',
        'location-marker',
        'lock-closed',
        'lock-open',
        'login',
        'logout',
        'mail',
        'mail-open',
        'map',
        'menu',
        'menu-alt-one',
        'menu-alt-two',
        'menu-alt-three',
        'menu-alt-four',
        'microphone',
        'minus',
        'minus-circle',
        'moon',
        'music-note',
        'newspaper',
        'office-building',
        'paper-airplane',
        'paper-clip',
        'pause',
        'payment',
        'pencil',
        'pencil-alt',
        'phone',
        'phone-incoming',
        'phone-missed-call',
        'phone-outgoing',
        'photograph',
        'play',
        'plus',
        'plus-circle',
        'presentation-chart-bar',
        'presentation-chart-line',
        'printer',
        'puzzle-piece',
        'qr-code',
        'question-mark-circle',
        'receipt-refund',
        'receipt-tax',
        'refresh',
        'reply',
        'rewind',
        'rss',
        'save',
        'save-as',
        'scale',
        'scissors',
        'search',
        'search-circle',
        'selector',
        'server',
        'share',
        'shield-check',
        'shield-exclamation',
        'shopping-bag',
        'sort',
        'sort-ascending',
        'sort-descending',
        'sort-down',
        'sort-up',
        'sparkles',
        'speakerphone',
        'spinner',
        'star',
        'status-offline',
        'status-online',
        'stop',
        'sun',
        'support',
        'switch-horizontal',
        'switch-vertical',
        'table',
        'tag',
        'template',
        'terminal',
        'thumb-down',
        'thumb-up',
        'ticket',
        'times',
        'times-circle',
        'trash',
        'trending-down',
        'trending-up',
        'truck',
        'twitter',
        'twitter-square',
        'upload',
        'user',
        'user-circle',
        'user-group',
        'user-remove',
        'users',
        'variable',
        'video-camera',
        'view-boards',
        'view-grid',
        'view-grid-add',
        'view-list',
        'volume-off',
        'volume-up',
        'vuesion',
        'wifi',
        'zoom-in',
        'zoom-out',
      ].sort();
    },
  },
};
</script>

<style lang="scss" module>
@import '~@/assets/_design-system';

.icons {
  .icon {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;

    i {
      width: $space-32;
      height: $space-32;
    }
  }
}
</style>
